### ISSUE TITLE
AttributeError when trying to save magnet link

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#682]
On http://kat.ph/ when right-clicking a magnet link and selecting "save as", this happens:

```
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/webpage.py", line 277, in on_download_requested
    download_manager.get_request(req, page=self)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/downloads.py", line 690, in get_request
    suggested_fn = utils.force_encoding(suggested_fn, encoding)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/utils.py", line 577, in force_encoding
    return text.encode(encoding, errors='replace').decode(encoding)
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by The-Compiler** [comment]
Bisected to 8f33fcfc52cf598d0aa11a347992c87010d3e37a.
